### ISSUE TITLE
CrudMock_Tests?

### ISSUE THREAD

**Issue by rygramer** [jamessimone/apex-mocks-stress-test#2]
Hey @jamessimone hope you had a nice Thanksgiving! I'm going through Joys of Apex top to bottom again. I noticed you referenced `CrudMock_Tests` in readme, but I couldn't find it in the source. Am I missing something?

**Comment by jamessimone** [comment]
Whoops - I will update this. I used to call the `DML` class `Crud` (and had a corresponding test class for that).

**Comment by jamessimone** [comment]
Ah, I have to correct myself - I updated it to `DML` (etc ...) in the [official standalone repo I have for this](https://github.com/jamessimone/apex-dml-mocking) (this repo has morphed more into "the backing code for joys of apex posts") but still have the old `Crud` nomenclature here. I'll simply update the `README` here.

**Comment by rygramer** [comment]
Ah gotcha, thanks for pointing me in the right direction
