### ISSUE TITLE
Concurrent writes and thread safety

### ISSUE THREAD

**Issue by joeythomaschaske** [jamessimone/apex-mocks-stress-test#3]
Hey I just read through your [blog here](https://www.jamessimone.net/blog/joys-of-apex/creating-a-round-robin-assignment/) about thread-safe reads/writes in Round Robin.

Could you clarify if/how this is truly read/write safe when 2 separate transactions commit at the same time? 

The solution seems to use cache timestamps against the repository initialized timestamps when committing, but there's not a mutex/semaphore around preventing 2 repositories from committing at the same time. The platform cache also [does not have a semaphore of its own](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_platform_cache_limitations.htm) to prevent concurrent reads/writes.
> Org cache supports concurrent reads and writes across multiple simultaneous Apex transactions. For example, a transaction updates the key PetName with the value Fido. At the same time, another transaction updates the same key with the value Felix. Both writes succeed, but one of the two values is chosen arbitrarily as the winner, and later transactions read that one value. However, this arbitrary choice is per key rather than per transaction. For example, suppose one transaction writes PetType="Cat" and PetName="Felix". Then, at the same moment, another transaction writes PetType="Dog" and PetName="Fido". In this case, the PetType winning value could be from the first transaction, and the PetName winning value could be from the second transaction. Subsequent get() calls on those keys would return PetType="Cat" and PetName="Fido".

It seems it's possible for 2 repositories to commit at the same time, which would read the same timestamp from the cache, and they would both succeed in committing using the same index.

Is this an edge case that's not covered?

I think a more resolute solution is to do away with the cache/timestamps and instead query the `RoundRobin__c` record with the `FOR UPDATE` clause in `assignOwners()`, do the assignment, update/release the `RoundRobin__c` for the next thread. You can then implement your recursive retry attempts if the platform throws a DML exception Or make a queueable where the  `assignOwners()` logic chains itself until it succeeds to avoid the recursive limit.

Interesting note from the docs for [FOR UPDATE](https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_for_update.htm):

> If you attempt to lock a record currently locked by another client, your process waits a maximum of 10 seconds for the lock to be released before acquiring a new lock. If the wait time exceeds 10 seconds, a QueryException is thrown. Similarly, if you attempt to update a record currently locked by another client and the lock isn’t released within a maximum of 10 seconds, a DmlException is thrown.

**Comment by jamessimone** [comment]
Mmm yes, that is possible. I think the `FOR UPDATE` suggestion is a good one, though having recently done something to this effect in Apex Rollup, one of the biggest issues with acquiring a lock in this manner on platform is the processing time required to handle the lock release (via handling the exception thrown). Switching to async for round robin is probably fine (for that specific scenario), but it comes with its own risks — namely, that downstream consumers on the primary thread are unable to perform additional logic against the assigned owners safely.

I will have to revise the article a bit to include more information. I have some thoughts about how to make the existing code thread-safe in the event that the time stamps match without having to resort to async.

**Comment by jamessimone** [comment]
Closing, updated the actual round robin repo based off of this issue having been opened and forgot to back-reference: https://github.com/jamessimone/salesforce-round-robin/pull/7
